# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateEKOP_cc <- function(nobs, alpha, epsilon, delta, mu, T) {
    .Call('mmstruct_simulateEKOP_cc', PACKAGE = 'mmstruct', nobs, alpha, epsilon, delta, mu, T)
}

simulateEKOPMis_cc <- function(nobs, alpha, epsilon, delta, mu, mis, T) {
    .Call('mmstruct_simulateEKOPMis_cc', PACKAGE = 'mmstruct', nobs, alpha, epsilon, delta, mu, mis, T)
}

