// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// simulateEKOP_cc
arma::imat simulateEKOP_cc(const unsigned int nobs, const double alpha, const double epsilon, const double delta, const double mu, const double T);
RcppExport SEXP mmstruct_simulateEKOP_cc(SEXP nobsSEXP, SEXP alphaSEXP, SEXP epsilonSEXP, SEXP deltaSEXP, SEXP muSEXP, SEXP TSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        unsigned int nobs = Rcpp::as<unsigned int >(nobsSEXP);
        double alpha = Rcpp::as<double >(alphaSEXP);
        double epsilon = Rcpp::as<double >(epsilonSEXP);
        double delta = Rcpp::as<double >(deltaSEXP);
        double mu = Rcpp::as<double >(muSEXP);
        double T = Rcpp::as<double >(TSEXP);
        arma::imat __result = simulateEKOP_cc(nobs, alpha, epsilon, delta, mu, T);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// simulateEKOPMis_cc
arma::imat simulateEKOPMis_cc(const unsigned int nobs, const double alpha, const double epsilon, const double delta, const double mu, const double mis, const double T);
RcppExport SEXP mmstruct_simulateEKOPMis_cc(SEXP nobsSEXP, SEXP alphaSEXP, SEXP epsilonSEXP, SEXP deltaSEXP, SEXP muSEXP, SEXP misSEXP, SEXP TSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        unsigned int nobs = Rcpp::as<unsigned int >(nobsSEXP);
        double alpha = Rcpp::as<double >(alphaSEXP);
        double epsilon = Rcpp::as<double >(epsilonSEXP);
        double delta = Rcpp::as<double >(deltaSEXP);
        double mu = Rcpp::as<double >(muSEXP);
        double mis = Rcpp::as<double >(misSEXP);
        double T = Rcpp::as<double >(TSEXP);
        arma::imat __result = simulateEKOPMis_cc(nobs, alpha, epsilon, delta, mu, mis, T);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
